### ISSUE TITLE
Fatal error when upload the theme "Templates must contain valid Handlebars"

### ISSUE THREAD

**Issue by ulyssebottello** [TryGhost/Journal#9]
Hey team!

When I upload the zip file, I have an error that says

> Templates must contain valid Handlebars
> Oops! You seemed to have used invalid Handlebars syntax. This mostly happens, when you use a helper that is not supported.
> See the full list of available helpers [here](https://ghost.org/docs/api/handlebars-themes/).
> 
> Affected files:
> default.hbs: Missing helper: "match"
> index.hbs: Missing helper: "match"

Am I the only one?

**Comment by minimaluminium** [comment]
Hey @ulyssebottello,

The error message indicates that the `{{#match}}` isn't supported on the version of Ghost you're using on your site. Would you be able to update Ghost to the latest version and check again?

**Comment by ulyssebottello** [comment]
You're right, I've just come across your theme checker - and the error is limited to the 3.X versions, I think you can close the issue. Thank you @minimaluminium!
